# Site settings
title: Johan van der Molen Moris
description: 'PhD Statistics'
url: ''
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Johan van der Molen Moris'
  email: johan.vdmolen@mrc-bsu.cam.ac.uk
  twitter_username:johan_vdmolen
  #facebook_username:
  github_username:  jvandermolen
  #linkedin_username: 
  interests: [Bayesian Nonparametrics, Biostatistics, Machine Learning]

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', vendor]
