# Site settings
title: Jekyll-Uno
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/jekyll-uno'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Josh Gerdes'
  institution: 'Institution'
  email: josh@joshgerdes.com
  institutional_website: 'https://www.ph.ed.ac.uk/people/peter-higgs'
  google_scholar: 6tmn5WoAAAAJ
  twitter_username: joshgerdes
  facebook_username: joshgerdes
  github_username:  joshgerdes
  linkedin_username:  joshgerdes
  interests: [interest1, interest2, interest3]

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
